package com.beerapp.domain.enums;

public enum BeerType {
    ALE, //Ale is a general category of beer: You'll find sub-categories like brown ales or pale ales. This is the oldest style of beer, which dates back to antiquity. What distinguishes an ale - and also makes this category of beer accessible for home brewers - is a warm-temperature fermentation for a relatively short period of time. In the brewing process, brewers introduce top-fermenting yeasts which, as the name suggests, ferment on the top of the brew. The fermentation process turns what would otherwise be a barley and malt tea into a boozy beverage.
    LAGER, //Lagers are a newer style of beer with two key differences from ales. Lagers ferment for a long time at a low temperature, and they rely on bottom-fermenting yeasts, which sink to the bottom of the fermenting tank to do their magic. Lagers are common among European countries, including Czechia, Germany, and the Netherlands, as well as in Canada, where they make up more than half of all beer sales.
    PORTER, //A type of ale, porter beers are known for their dark black color and roasted malt aroma and notes. Porters may be fruity or dry in flavor, which is determined by the variety of roasted malt used in the brewing process.
    STOUT, //Like porters, stouts are dark, roasted ales. Stouts taste less sweet than porters and often feature a bitter coffee taste, which comes from unmalted roasted barley that is added to the wort. They are characterized by a thick, creamy head. Ireland's Guinness may be one of the world's best-known stouts.
    BLONDE_ALE, //This easy drinking ale is a summer favorite, thanks to its light malt sweetness and trace of hops, which add aroma. As the name suggests, blonde ales have a pale color and a clear body. They tend to be crisp and dry, with few traces of bitterness, rather than hop-heavy or dank.
    BROWN_ALE, //Brown ales range in color from amber to brown, with chocolate, caramel, citrus, or nut notes. Brown ales are a bit of a mixed bag, since the different malts used and the country of origin can greatly affect the flavor and scent of this underrated beer style.
    PALE_ALE, //An English style of ale, pale ales and known for their copper color and fruity scent. Don't let the name fool you: these beers are strong enough to pair well with spicy foods. Related to the pale is the APA, or American Pale Ale, which is somewhat of a hybrid between the traditional English pale ale and the IPA style. American pale ales are hoppier and usually feature American two row malt.
    IPA, //Originally, India Pale Ale or IPA was a British pale ale brewed with extra hops. High levels of this bittering agent made the beer stable enough to survive the long boat trip to India without spoiling. The extra dose of hops gives IPA beers their bitter taste. Depending on the style of hops used, IPAs may have fruit-forward citrus flavors or taste of resin and pine. American brewers have taken the IPA style and run with it, introducing unusual flavors and ingredients to satisfy U.S. beer drinkers' love for the brew style.
    WHEAT, //An easy-drinking, light style of beer, wheat beers are known for a soft, smooth flavor and a hazy body. Wheat beers tend to taste like spices or citrus, with the hefeweizen or unfiltered wheat beer being one of the more common styles.
    PILSNER, //A subspecies of lager, pilsner beers are distinguished by their water, which varies from neutral too hard. Pilsners are among the hoppiest lagers and generally have a dry, slightly bitter flavor. Their light golden color, clear body, and crisp finish make Pilsners a popular summer beer.
    SOUR_ALE //An ancient style of beer that's taken off in popularity in recent years, sour ales are crafted from wild yeasts, much like sourdough bread. These beers are known for a tart tang that pairs well with tropical fruit and spices. Within sour beers, you'll find lambics, which are Belgian sour beers mixed with fruit, goses, a German sour beer made with coriander and sea salt, and Flanders, a Belgian sour beer fermented in wood tanks.
}

// source: https://hospitalityinsights.ehl.edu/beer-types