CREATE TABLE IF NOT EXISTS `users` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `email` VARCHAR(100) NOT NULL,
    `password` VARCHAR(500) NOT NULL,
    `role` ENUM('ADMIN', 'USER'),
    `sign_up_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);